# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: /tmp/redux-persistence

    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install node dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Build library
          command: npm run build
      - run:
          name: Run tests
          command: npm run test
      - save_cache:
          paths:
            - dist
          key: dist-{{ .Branch }}-{{ .Revision }}

  release:
    docker:
      - image: circleci/node:10

    working_directory: /tmp/redux-persistence

    steps:
      - checkout
      - restore_cache:
          keys:
            - dist-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install node dependencies
          command: npm install
      - run:
          name: Semantic release
          command: npm run semantic-release

workflows:
  version: 2
  build-deploy-release:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
